/**
 * `src/lib/parse.ts` — `Parse CSV`, `To CSV`, `Parse XML` and `Parse Feed`, emitted into the app (EXP-011 §75).
 *
 * The same shape as {@link ./utilLib.ts}: constant text, shipped only where a component calls into it, and a
 * **separate** module from `util.ts` on that file's own rule (a project that formats a string should not ship
 * a CSV tokeniser, and an XML parser even less). The four are `util-call`s in the plan — each node is a
 * function of its inputs and holds nothing else — with one difference from the three small utilities:
 * every one of them has SEVERAL value outputs, so the call carries the output port's name as its trailing
 * literal argument (`DATE_NODES`' selector, one family over) and the helper answers that port. A one-entry
 * memo inside each helper keeps a page that reads three outputs of one node to one parse.
 *
 * A transcription of three runtime modules and four node files:
 *
 * - `noodl-runtime/src/csv.ts` — `stripBOM`, the contiguity-checking `tokenise`, `parseCSV` (the
 *   unterminated-quote sentence verbatim), `rowsToRecords`, `unionOfKeys`, `quoteCell`, `toCSV`, `rowsToCSV`.
 * - `data/parsecsv.ts` / `data/tocsv.ts` — the abstain (`textSupplied` / `itemsSupplied`: nothing arrived ⇒
 *   no Items, Count 0, no Error — Failure Contract §2), the setters' fallbacks (`delimiter || ','`,
 *   `!!hasHeader`, a `stringlist` Columns split on commas and trimmed), rows-of-cells written cell for cell.
 * - `noodl-runtime/src/xml.ts` — `scanForHostileConstructs` (the two refusals, sentences verbatim) and
 *   `parseXML` over **`fast-xml-parser` at the interpreter's own pin, 4.5.7**, with the interpreter's own
 *   options. 🔴 The one third-party dependency an emitted lib has ever declared: FED-001 R1 took the library
 *   over a hand-rolled scanner for the runtime (entity expansion is a denial-of-service hole, not a wrong
 *   answer), and a transcription of an XML parser would be a second parser that drifts — so
 *   {@link PARSE_DEPENDENCIES} is added to the exported `package.json` exactly when a component calls
 *   `parseXml` or `parseFeed`.
 * - `noodl-runtime/src/feed.ts` — the whole module: RSS/Atom/RDF detection (RDF first, its `<item>` a
 *   SIBLING of `<channel>`), the readers, `toISODate`'s retry, the Atom link family, images, enclosures,
 *   tags, authors, the identity ladder and FNV-1a `hashId`. 🔴 **The ladder's separator is a NUL byte.**
 *   `feed.ts:365` holds a literal U+0000 between the quotes, which every editor draws as a space; the
 *   transcription writes `'\u0000'` because FED-002's unique index keys on the id and a space would mint a
 *   different id for every item on the hash rung. Found by the §A differential, not by reading.
 *
 * ⚠️ **The one divergence, and where it is reported.** On a FAILED parse the interpreter keeps the previous
 * successful answer on its value outputs beside the Error (`items` is "replaced only on a successful
 * parse"); a pure call has no previous answer, so Items is absent and Count is 0 beside the Error. The
 * planner files a note at every parse node whose text arrives by wire — a literal cannot have a previous
 * parse. On a FIRST failure the two agree exactly.
 *
 * `Changed` and `Failure` are recomputation pulses and defer with the date family's sentence
 * ({@link PARSE_SIGNAL_SENTENCES}); a wire off one is not a chain the export can hang anything on.
 */

/** Where the module lands in the exported app. */
export const PARSE_LIB_PATH = 'src/lib/parse.ts';

/** The exported helpers, one per node. Sorted — the import list is sorted too. */
export const PARSE_HELPERS = ['parseCsv', 'parseFeed', 'parseXml', 'toCsv'] as const;

export type ParseHelper = (typeof PARSE_HELPERS)[number];

export function isParseHelper(fn: string): fn is ParseHelper {
  return (PARSE_HELPERS as readonly string[]).includes(fn);
}

/**
 * The npm dependency the exported app takes on when XML is parsed — the interpreter's own pin
 * (`noodl-runtime/package.json`, `xml.ts`'s module comment measured 4.5.7 at 230 KB unpacked with one dep
 * against 5.x's 1.3 MB with six). Exact, not a caret, so the exported app and the interpreter read one parser.
 */
export const PARSE_DEPENDENCIES: Readonly<Record<string, string>> = { 'fast-xml-parser': '4.5.7' };

/** Which helpers need {@link PARSE_DEPENDENCIES}. `parseCsv` and `toCsv` need nothing. */
export const PARSE_HELPERS_NEEDING_DEPENDENCY: ReadonlySet<string> = new Set(['parseXml', 'parseFeed']);

/**
 * Per output port: the static TypeScript type the helper's overload answers (`exprTsType`'s vocabulary —
 * `unknown` wherever the value can be `undefined`, for `dateToString`'s reason: a single-placeholder String
 * Format collapses a `string`-typed expression to the bare value, and that would print the word
 * "undefined" where the interpreter substitutes `''`), and whether it can be `undefined` at all
 * (`maybeUndefinedExpr`'s table, one family over).
 *
 * 🔴 Must agree with the overloads in {@link parseLibSource}. `items` is `any[]` on both CSV and Feed —
 * the CSV rows' shape depends on Has Header, and the feed rows are typed inside the module only, so the
 * emitted component never has to name a type it does not import. {@link FEED_ITEM_FIELDS} is what lets a
 * repeater over a feed drop a mapped field the rows do not carry, by name.
 */
export const PARSE_OUTPUTS: Readonly<Record<ParseHelper, Readonly<Record<string, { tsType: string; maybeUndefined: boolean }>>>> = {
  parseCsv: {
    items: { tsType: 'any[]', maybeUndefined: true },
    count: { tsType: 'number', maybeUndefined: false },
    error: { tsType: 'unknown', maybeUndefined: true }
  },
  toCsv: {
    text: { tsType: 'string', maybeUndefined: false },
    count: { tsType: 'number', maybeUndefined: false }
  },
  parseXml: {
    result: { tsType: 'unknown', maybeUndefined: true },
    error: { tsType: 'unknown', maybeUndefined: true },
    errorCode: { tsType: 'unknown', maybeUndefined: true }
  },
  parseFeed: {
    items: { tsType: 'any[]', maybeUndefined: true },
    count: { tsType: 'number', maybeUndefined: false },
    feedTitle: { tsType: 'string', maybeUndefined: false },
    feedLink: { tsType: 'string', maybeUndefined: false },
    feedDescription: { tsType: 'string', maybeUndefined: false },
    feedUpdated: { tsType: 'unknown', maybeUndefined: true },
    kind: { tsType: 'string', maybeUndefined: false },
    source: { tsType: 'string', maybeUndefined: false },
    error: { tsType: 'unknown', maybeUndefined: true },
    errorCode: { tsType: 'unknown', maybeUndefined: true }
  }
};

/** The fields every feed item carries (`FeedItem` in the emitted module; `parsefeed.ts`'s Items description). */
export const FEED_ITEM_FIELDS: readonly string[] = [
  'id',
  'title',
  'link',
  'published',
  'updated',
  'author',
  'summary',
  'content',
  'image',
  'enclosure',
  'tags',
  'raw'
];

/**
 * The selector a `util-call` into this module carries: its trailing literal argument. `undefined` for a
 * call that is not a parse helper, or whose last argument is not a string literal — neither can be built by
 * the planner, so a lookup that answers `undefined` is a programming error upstream, not an authored shape.
 */
export function parseSelectorOf(expr: { fn: string; args: ReadonlyArray<{ kind: string; value?: unknown }> }): string | undefined {
  if (!isParseHelper(expr.fn)) return undefined;
  const last = expr.args[expr.args.length - 1];
  return last !== undefined && last.kind === 'literal' && typeof last.value === 'string' ? last.value : undefined;
}

/** `exprTsType` for a parse call — `unknown` for a selector the table does not know, never a throw. */
export function parseOutputTsType(fn: ParseHelper, selector: string | undefined): string {
  return (selector !== undefined && PARSE_OUTPUTS[fn][selector]?.tsType) || 'unknown';
}

/** `maybeUndefinedExpr` for a parse call — `true` for a selector the table does not know: the guarded answer. */
export function parseOutputMayBeUndefined(fn: ParseHelper, selector: string | undefined): boolean {
  return selector === undefined ? true : (PARSE_OUTPUTS[fn][selector]?.maybeUndefined ?? true);
}

/**
 * The deferral sentence for a signal output consumed as a wire — the date family's `DATE_SIGNAL_OUTPUTS`,
 * one family over, and for the same reason: `Changed` and `Failure` announce a recomputation, and a
 * recomputation in the emitted component is a render, not an event a chain can hang off. `Failure` is a
 * value this slice renders as an absent one (the Error output) rather than a pulse it can fire.
 */
export const PARSE_SIGNAL_SENTENCES: Readonly<Record<string, string>> = {
  changed:
    'its Changed output is consumed — that pulse announces a recomputation, and a recomputation in the emitted component is a render, not an event a chain can hang off',
  failure:
    'its Failure output is consumed — the node re-parses on every arrival, so the failure is a value this slice renders as an absent one (read its Error output) rather than a pulse it can fire'
};

/**
 * The module's source.
 *
 * ⚠️ A plain string array rather than a template literal, for `dateLib.ts`'s stated reason: the emitted body
 * needs no interpolation, and keeping it out of an interpolation context means a future edit cannot
 * accidentally interpolate the generator's own scope into the exported app. Generated from a real `.ts`
 * file that was typechecked under the exported app's own strict options and graded against the runtime
 * modules by `tests/the-parsers.test.ts` §A; edit the strings and the test grades the edit.
 */
export function parseLibSource(): string {
  return [
    "//",
    "// The four parsers — Parse CSV, To CSV, Parse XML and Parse Feed — transcribed from the interpreter they",
    "// have to agree with: noodl-runtime/src/{csv,xml,feed}.ts and the four node files under",
    "// noodl-runtime/src/nodes/std-library/data/. Each helper is one node: its arguments are the node's input",
    "// ports in panel order, the last argument names the OUTPUT port being read, and the answer is what that",
    "// port holds after the node has parsed the same inputs.",
    "//",
    "// Every one of these nodes is a function of its inputs — it re-parses whenever an input arrives, and holds",
    "// nothing else — so each is a pure call here, and a page that reads three outputs of one node makes three",
    "// calls. A one-entry memo per helper keeps that to one parse per distinct input.",
    "//",
    "// Two rules the nodes state, kept here: EVERY VALUE IS A STRING (a CSV column that looks numeric is \"42\";",
    "// an XML <guid>0123</guid> stays \"0123\"), and NOTHING HERE THROWS — a document that cannot be read answers",
    "// through its Error output, because a graph has nowhere to catch an exception and neither does a page.",
    "//",
    "// XML is read by fast-xml-parser 4.5.7 — the library the interpreter itself uses, at the version it pins —",
    "// because a second XML parser is a second answer. CSV is the interpreter's own tokeniser, transcribed.",
    "//",
    "// Where the two deliberately differ, and it is one place: on a FAILED parse the interpreter keeps the",
    "// previous successful answer on its value outputs beside the Error, and a pure call has no previous",
    "// answer to keep — Items is absent and Count is 0 beside the Error. The export reports that at every",
    "// node whose text arrives by wire.",
    "//",
    "",
    "import { XMLParser } from 'fast-xml-parser';",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// CSV — noodl-runtime/src/csv.ts, verbatim in substance",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "interface CSVParseError {",
    "  message: string;",
    "  /** 1-based line of the input where the tokeniser gave up. */",
    "  line: number;",
    "}",
    "",
    "interface CSVParseResult {",
    "  rows: string[][];",
    "  error?: CSVParseError;",
    "}",
    "",
    "/** Excel writes UTF-8 with a BOM, and the BOM lands on the first header cell. */",
    "function stripBOM(text: string): string {",
    "  return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;",
    "}",
    "",
    "/**",
    " * The scanner. `gapAt` is the first character it SKIPPED: `exec` with the `g` flag scans forward past text",
    " * it cannot match, so an unterminated quote does not truncate the file — it silently swallows a word and",
    " * carries on. Contiguity is the property that fails, so each match has to begin where the last one ended.",
    " */",
    "function tokenise(text: string, delimiter: string): { rows: string[][]; gapAt?: number } {",
    "  const objPattern = new RegExp(",
    "    '(\\\\' + delimiter + '|\\\\r?\\\\n|\\\\r|^)' + '(?:\"([^\"]*(?:\"\"[^\"]*)*)\"|' + '([^\"\\\\' + delimiter + '\\\\r\\\\n]*))',",
    "    'gi'",
    "  );",
    "  const rows: string[][] = [[]];",
    "  let matches: RegExpExecArray | null = null;",
    "  let prevLastIndex: number | undefined;",
    "  let expected = 0;",
    "  let gapAt: number | undefined;",
    "  // The zero-progress guard is load-bearing: the standard-field group can match the empty string.",
    "  while ((matches = objPattern.exec(text)) && prevLastIndex !== objPattern.lastIndex) {",
    "    prevLastIndex = objPattern.lastIndex;",
    "    if (gapAt === undefined && matches.index > expected) gapAt = expected;",
    "    expected = objPattern.lastIndex;",
    "    const matchedDelimiter = matches[1];",
    "    if (matchedDelimiter.length && matchedDelimiter !== delimiter) rows.push([]);",
    "    // `!== undefined`, not truthiness: `\"\"` is a quoted cell whose capture is the empty string.",
    "    const value = matches[2] !== undefined ? matches[2].replace(/\"\"/g, '\"') : matches[3];",
    "    rows[rows.length - 1].push(value);",
    "  }",
    "  if (gapAt === undefined && expected < text.length) gapAt = expected;",
    "  return { rows, gapAt };",
    "}",
    "",
    "function parseCSVText(text: unknown, delimiter: string): CSVParseResult {",
    "  const source = stripBOM(String(text === undefined || text === null ? '' : text));",
    "  const { rows, gapAt } = tokenise(source, delimiter);",
    "  if (gapAt !== undefined) {",
    "    const line = source.slice(0, gapAt).split(/\\r\\n|\\r|\\n/).length;",
    "    return {",
    "      rows,",
    "      error: {",
    "        line,",
    "        message:",
    "          `The CSV could not be parsed at line ${line}: a quote is never closed, so text around it ` +",
    "          'would have been silently dropped. A quote inside a quoted cell has to be written as \"\".'",
    "      }",
    "    };",
    "  }",
    "  return { rows };",
    "}",
    "",
    "/** Header row + data rows → records. A row shorter than the header leaves the missing columns undefined. */",
    "function rowsToRecords(rows: string[][]): Record<string, string>[] {",
    "  const header = rows[0];",
    "  if (!header) return [];",
    "  const records: Record<string, string>[] = [];",
    "  for (let i = 1; i < rows.length; i++) {",
    "    const row = rows[i];",
    "    const record: Record<string, string> = {};",
    "    for (let j = 0; j < header.length; j++) record[header[j]] = row[j];",
    "    records.push(record);",
    "  }",
    "  return records;",
    "}",
    "",
    "/** The union of every record's keys, in the order they were first seen. */",
    "function unionOfKeys(records: Record<string, unknown>[]): string[] {",
    "  const seen: string[] = [];",
    "  const index: Record<string, true> = {};",
    "  for (const record of records) {",
    "    if (!record) continue;",
    "    for (const key of Object.keys(record)) {",
    "      if (index[key]) continue;",
    "      index[key] = true;",
    "      seen.push(key);",
    "    }",
    "  }",
    "  return seen;",
    "}",
    "",
    "/** One cell, quoted only where it has to be: the delimiter, a quote or a newline inside it. */",
    "function quoteCell(value: unknown, delimiter: string): string {",
    "  if (value === undefined || value === null) return '';",
    "  const text = typeof value === 'string' ? value : String(value);",
    "  const needsQuoting = text.indexOf(delimiter) !== -1 || /[\"\\r\\n]/.test(text);",
    "  return needsQuoting ? '\"' + text.replace(/\"/g, '\"\"') + '\"' : text;",
    "}",
    "",
    "function recordsToCSV(",
    "  records: Record<string, unknown>[],",
    "  options: { columns?: string[]; delimiter: string; includeHeader: boolean }",
    "): string {",
    "  const delimiter = options.delimiter;",
    "  const columns = options.columns && options.columns.length ? options.columns : unionOfKeys(records);",
    "  const lines: string[] = [];",
    "  if (options.includeHeader) lines.push(columns.map((c) => quoteCell(c, delimiter)).join(delimiter));",
    "  for (const record of records) {",
    "    lines.push(columns.map((c) => quoteCell(record ? record[c] : undefined, delimiter)).join(delimiter));",
    "  }",
    "  return lines.join('\\n');",
    "}",
    "",
    "function rowsToCSV(rows: unknown[][], delimiter: string): string {",
    "  return rows.map((row) => (row || []).map((cell) => quoteCell(cell, delimiter)).join(delimiter)).join('\\n');",
    "}",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// Parse CSV — parsecsv.ts",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "/** The node's value outputs. `Changed` and `Failure` are pulses, and a pulse is a render here, not an event. */",
    "export type ParseCsvOutput = 'items' | 'count' | 'error';",
    "",
    "interface ParseCsvState {",
    "  items: unknown[] | undefined;",
    "  count: number;",
    "  error: string | undefined;",
    "}",
    "",
    "let lastCsv: { text: unknown; hasHeader: unknown; delimiter: unknown; state: ParseCsvState } | undefined;",
    "",
    "function parseCsvState(text: unknown, hasHeader: unknown, delimiter: unknown): ParseCsvState {",
    "  if (lastCsv && lastCsv.text === text && lastCsv.hasHeader === hasHeader && lastCsv.delimiter === delimiter) {",
    "    return lastCsv.state;",
    "  }",
    "  let state: ParseCsvState;",
    "  // Nothing has arrived on CSV: the node abstains — no Items, a Count of 0, no Error (Failure Contract §2).",
    "  if (text === undefined || text === null) {",
    "    state = { items: undefined, count: 0, error: undefined };",
    "  } else {",
    "    // The setter is `value || ','`: a cleared Delimiter is a comma, not an empty separator.",
    "    const result = parseCSVText(text, delimiter ? String(delimiter) : ',');",
    "    if (result.error) {",
    "      state = { items: undefined, count: 0, error: result.error.message };",
    "    } else if (hasHeader) {",
    "      const records = rowsToRecords(result.rows);",
    "      state = { items: records, count: records.length, error: undefined };",
    "    } else {",
    "      // Rows of cells stay plain nested arrays: a row of strings is not a record.",
    "      state = { items: result.rows, count: result.rows.length, error: undefined };",
    "    }",
    "  }",
    "  lastCsv = { text, hasHeader, delimiter, state };",
    "  return state;",
    "}",
    "",
    "/**",
    " * `Parse CSV` — the text as records (Has Header ticked) or rows of cells, with its Count and its Error.",
    " *",
    " * Every cell is a string. A malformed CSV (a quote never closed) is an Error naming the line, and no Items.",
    " */",
    "export function parseCsv(text: unknown, hasHeader: unknown, delimiter: unknown, output: 'items'): any[] | undefined;",
    "export function parseCsv(text: unknown, hasHeader: unknown, delimiter: unknown, output: 'count'): number;",
    "export function parseCsv(text: unknown, hasHeader: unknown, delimiter: unknown, output: 'error'): string | undefined;",
    "export function parseCsv(text: unknown, hasHeader: unknown, delimiter: unknown, output: ParseCsvOutput): unknown {",
    "  return parseCsvState(text, hasHeader, delimiter)[output];",
    "}",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// To CSV — tocsv.ts",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "export type ToCsvOutput = 'text' | 'count';",
    "",
    "interface ToCsvState {",
    "  text: string;",
    "  count: number;",
    "}",
    "",
    "let lastToCsv:",
    "  | { items: unknown; columns: unknown; delimiter: unknown; includeHeader: unknown; state: ToCsvState }",
    "  | undefined;",
    "",
    "function toCsvState(items: unknown, columns: unknown, delimiter: unknown, includeHeader: unknown): ToCsvState {",
    "  if (",
    "    lastToCsv &&",
    "    lastToCsv.items === items &&",
    "    lastToCsv.columns === columns &&",
    "    lastToCsv.delimiter === delimiter &&",
    "    lastToCsv.includeHeader === includeHeader",
    "  ) {",
    "    return lastToCsv.state;",
    "  }",
    "  let state: ToCsvState;",
    "  // Nothing has arrived on Items: the node abstains — the empty text `initialize` writes, a Count of 0.",
    "  if (items === undefined || items === null) {",
    "    state = { text: '', count: 0 };",
    "  } else {",
    "    const source = items as ArrayLike<unknown>;",
    "    const length = source.length || 0;",
    "    const list: unknown[] = [];",
    "    for (let i = 0; i < length; i++) list.push(source[i]);",
    "    const sep = delimiter ? String(delimiter) : ',';",
    "    // A `stringlist` port carries ONE comma-separated string; the trim makes `name, team` mean `name,team`.",
    "    const declared = String(columns === undefined || columns === null ? '' : columns)",
    "      .split(',')",
    "      .map((c) => c.trim())",
    "      .filter((c) => c.length > 0);",
    "    // Rows of cells — what Parse CSV produces with Has Header unticked — are written cell for cell.",
    "    const isRowsOfCells = list.length > 0 && list.every((item) => Array.isArray(item));",
    "    const text = isRowsOfCells",
    "      ? rowsToCSV(list as unknown[][], sep)",
    "      : recordsToCSV(",
    "          list.map((item) => (item === null || item === undefined ? {} : Object.assign({}, item as Record<string, unknown>))),",
    "          { columns: declared.length ? declared : undefined, delimiter: sep, includeHeader: !!includeHeader }",
    "        );",
    "    state = { text, count: length };",
    "  }",
    "  lastToCsv = { items, columns, delimiter, includeHeader, state };",
    "  return state;",
    "}",
    "",
    "/**",
    " * `To CSV` — an array as CSV text, with its Count. Cells containing the delimiter, a quote or a newline are",
    " * quoted and their quotes doubled, so the text round-trips through `parseCsv` unchanged.",
    " */",
    "export function toCsv(items: unknown, columns: unknown, delimiter: unknown, includeHeader: unknown, output: 'text'): string;",
    "export function toCsv(items: unknown, columns: unknown, delimiter: unknown, includeHeader: unknown, output: 'count'): number;",
    "export function toCsv(items: unknown, columns: unknown, delimiter: unknown, includeHeader: unknown, output: ToCsvOutput): unknown {",
    "  return toCsvState(items, columns, delimiter, includeHeader)[output];",
    "}",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// XML — noodl-runtime/src/xml.ts",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "type XMLErrorCode = 'xml/too-large' | 'xml/entity-declaration' | 'xml/doctype-subset' | 'xml/parse-failed' | 'xml/empty';",
    "",
    "interface XMLParseError {",
    "  message: string;",
    "  code: XMLErrorCode;",
    "}",
    "",
    "interface XMLParseResult {",
    "  value?: Record<string, unknown>;",
    "  error?: XMLParseError;",
    "}",
    "",
    "/** Five million characters — the string is what costs the heap. */",
    "const DEFAULT_MAX_BYTES = 5 * 1024 * 1024;",
    "",
    "/** The key fast-xml-parser gives a tag's own text when it also carries attributes. */",
    "const TEXT_KEY = '#text';",
    "",
    "/**",
    " * A pre-parse scan for the two constructs that make parsing itself unsafe: an entity declaration (the",
    " * billion-laughs expansion) and a DOCTYPE with an internal subset, which is where such declarations live.",
    " * The prolog is read, not the document — a match after the root opens is not a declaration.",
    " */",
    "function scanForHostileConstructs(text: string): XMLParseError | undefined {",
    "  const head = text.slice(0, 64 * 1024);",
    "  if (/<!ENTITY/i.test(head)) {",
    "    return {",
    "      code: 'xml/entity-declaration',",
    "      message:",
    "        'This XML declares its own entities (<!ENTITY). They are refused, not expanded, because a ' +",
    "        'few lines of nested declarations expand to gigabytes and take the process with them. No ' +",
    "        'feed format needs them'",
    "    };",
    "  }",
    "  if (/<!DOCTYPE[^>[]*\\[/i.test(head)) {",
    "    return {",
    "      code: 'xml/doctype-subset',",
    "      message:",
    "        'This XML carries an inline DOCTYPE subset (<!DOCTYPE … [ … ]). It is refused rather than ' +",
    "        'read, because that is the only place a document can define entities that expand'",
    "    };",
    "  }",
    "  return undefined;",
    "}",
    "",
    "function parseXMLText(",
    "  text: unknown,",
    "  options: { attributePrefix: string; alwaysArray: string[]; trimValues: boolean; maxBytes: number }",
    "): XMLParseResult {",
    "  if (typeof text !== 'string' || text.trim() === '') {",
    "    return { error: { code: 'xml/empty', message: 'There was no XML to parse — the text was empty' } };",
    "  }",
    "  if (text.length > options.maxBytes) {",
    "    return {",
    "      error: {",
    "        code: 'xml/too-large',",
    "        message:",
    "          `This XML is ${Math.round(text.length / 1024)} KB, over the ${Math.round(options.maxBytes / 1024)} KB ` +",
    "          'limit. Raise Max Bytes on the node if the source really is this big'",
    "      }",
    "    };",
    "  }",
    "  const hostile = scanForHostileConstructs(text);",
    "  if (hostile) return { error: hostile };",
    "  const alwaysArray = options.alwaysArray;",
    "  const parser = new XMLParser({",
    "    attributeNamePrefix: options.attributePrefix,",
    "    ignoreAttributes: false,",
    "    // Namespace prefixes are KEPT: `content:encoded` and `yt:videoId` are how a reader tells sources apart.",
    "    removeNSPrefix: false,",
    "    trimValues: options.trimValues,",
    "    parseTagValue: false,",
    "    parseAttributeValue: false,",
    "    processEntities: true,",
    "    htmlEntities: true,",
    "    textNodeName: TEXT_KEY,",
    "    isArray: (name: string) => alwaysArray.indexOf(name) !== -1",
    "  });",
    "  try {",
    "    const value = parser.parse(text) as Record<string, unknown>;",
    "    if (!value || typeof value !== 'object') {",
    "      return { error: { code: 'xml/parse-failed', message: 'This text is not XML' } };",
    "    }",
    "    return { value };",
    "  } catch (e) {",
    "    const message = e && (e as Error).message ? (e as Error).message : String(e);",
    "    return { error: { code: 'xml/parse-failed', message } };",
    "  }",
    "}",
    "",
    "/** The setter's rule, shared by both XML nodes: a finite positive number, else the default. */",
    "function maxBytesOf(value: unknown): number {",
    "  const n = Number(value);",
    "  return isFinite(n) && n > 0 ? n : DEFAULT_MAX_BYTES;",
    "}",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// Parse XML — parsexml.ts",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "export type ParseXmlOutput = 'result' | 'error' | 'errorCode';",
    "",
    "interface ParseXmlState {",
    "  result: Record<string, unknown> | undefined;",
    "  error: string | undefined;",
    "  errorCode: string | undefined;",
    "}",
    "",
    "let lastXml:",
    "  | { text: unknown; attributePrefix: unknown; alwaysArray: unknown; trimValues: unknown; maxBytes: unknown; state: ParseXmlState }",
    "  | undefined;",
    "",
    "function parseXmlState(",
    "  text: unknown,",
    "  attributePrefix: unknown,",
    "  alwaysArray: unknown,",
    "  trimValues: unknown,",
    "  maxBytes: unknown",
    "): ParseXmlState {",
    "  if (",
    "    lastXml &&",
    "    lastXml.text === text &&",
    "    lastXml.attributePrefix === attributePrefix &&",
    "    lastXml.alwaysArray === alwaysArray &&",
    "    lastXml.trimValues === trimValues &&",
    "    lastXml.maxBytes === maxBytes",
    "  ) {",
    "    return lastXml.state;",
    "  }",
    "  let state: ParseXmlState;",
    "  if (text === undefined || text === null) {",
    "    state = { result: undefined, error: undefined, errorCode: undefined };",
    "  } else {",
    "    const parsed = parseXMLText(text, {",
    "      // The setter keeps an empty prefix: only an absent one is `@`.",
    "      attributePrefix: attributePrefix === undefined || attributePrefix === null ? '@' : String(attributePrefix),",
    "      alwaysArray: String(alwaysArray || '')",
    "        .split(',')",
    "        .map((s) => s.trim())",
    "        .filter(Boolean),",
    "      trimValues: !!trimValues,",
    "      maxBytes: maxBytesOf(maxBytes)",
    "    });",
    "    state = parsed.error",
    "      ? { result: undefined, error: parsed.error.message, errorCode: parsed.error.code }",
    "      : { result: parsed.value, error: undefined, errorCode: undefined };",
    "  }",
    "  lastXml = { text, attributePrefix, alwaysArray, trimValues, maxBytes, state };",
    "  return state;",
    "}",
    "",
    "/**",
    " * `Parse XML` — the document as an object, or why it could not be read. Every value is a string; a tag",
    " * carrying both attributes and text becomes `{ \"@attr\": \"…\", \"#text\": \"…\" }`.",
    " */",
    "export function parseXml(",
    "  text: unknown,",
    "  attributePrefix: unknown,",
    "  alwaysArray: unknown,",
    "  trimValues: unknown,",
    "  maxBytes: unknown,",
    "  output: 'result'",
    "): Record<string, unknown> | undefined;",
    "export function parseXml(",
    "  text: unknown,",
    "  attributePrefix: unknown,",
    "  alwaysArray: unknown,",
    "  trimValues: unknown,",
    "  maxBytes: unknown,",
    "  output: 'error' | 'errorCode'",
    "): string | undefined;",
    "export function parseXml(",
    "  text: unknown,",
    "  attributePrefix: unknown,",
    "  alwaysArray: unknown,",
    "  trimValues: unknown,",
    "  maxBytes: unknown,",
    "  output: ParseXmlOutput",
    "): unknown {",
    "  return parseXmlState(text, attributePrefix, alwaysArray, trimValues, maxBytes)[output];",
    "}",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// Feeds — noodl-runtime/src/feed.ts",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "type FeedKind = 'rss' | 'atom' | 'rdf';",
    "type FeedSource = 'youtube' | 'reddit' | 'podcast' | 'generic';",
    "",
    "interface FeedEnclosure {",
    "  url: string;",
    "  type?: string;",
    "  length?: string;",
    "}",
    "",
    "/** One item, whatever the feed's format. `id` is never empty — the guid, the Atom id, the link, or a hash. */",
    "export interface FeedItem {",
    "  id: string;",
    "  title: string;",
    "  link: string;",
    "  published: string | null;",
    "  updated: string | null;",
    "  author: string;",
    "  summary: string;",
    "  /** Whatever HTML the feed shipped, unsanitised — sanitising belongs to what renders it. */",
    "  content: string;",
    "  image: string;",
    "  enclosure: FeedEnclosure | null;",
    "  tags: string[];",
    "  raw: Record<string, unknown>;",
    "}",
    "",
    "interface FeedMeta {",
    "  title: string;",
    "  link: string;",
    "  description: string;",
    "  updated: string | null;",
    "  kind: FeedKind;",
    "  source: FeedSource;",
    "}",
    "",
    "interface FeedParseResult {",
    "  feed?: FeedMeta;",
    "  items?: FeedItem[];",
    "  error?: XMLParseError | { code: 'feed/unrecognised'; message: string };",
    "}",
    "",
    "const FEED_ARRAY_TAGS = ['item', 'entry', 'link', 'category', 'enclosure', 'media:content', 'media:thumbnail', 'content'];",
    "",
    "type Node = Record<string, unknown>;",
    "",
    "function isObject(v: unknown): v is Node {",
    "  return !!v && typeof v === 'object' && !Array.isArray(v);",
    "}",
    "",
    "function one(node: unknown, key: string): unknown {",
    "  if (!isObject(node)) return undefined;",
    "  const v = node[key];",
    "  return Array.isArray(v) ? v[0] : v;",
    "}",
    "",
    "function many(node: unknown, key: string): unknown[] {",
    "  if (!isObject(node)) return [];",
    "  const v = node[key];",
    "  if (v === undefined || v === null) return [];",
    "  return Array.isArray(v) ? v : [v];",
    "}",
    "",
    "function pick(node: unknown, ...keys: string[]): unknown {",
    "  for (const key of keys) {",
    "    const v = one(node, key);",
    "    if (v !== undefined && v !== null) return v;",
    "  }",
    "  return undefined;",
    "}",
    "",
    "/** The text of a value, whatever shape it arrived in — a typed Atom title is `{ '@type', '#text' }`. */",
    "function text(value: unknown): string {",
    "  if (value === undefined || value === null) return '';",
    "  if (typeof value === 'string') return value;",
    "  if (typeof value === 'number' || typeof value === 'boolean') return String(value);",
    "  if (Array.isArray(value)) return text(value[0]);",
    "  if (isObject(value)) {",
    "    const inner = value[TEXT_KEY];",
    "    if (inner !== undefined) return text(inner);",
    "    return '';",
    "  }",
    "  return '';",
    "}",
    "",
    "function attr(node: unknown, name: string): string {",
    "  if (!isObject(node)) return '';",
    "  return text(node['@' + name]);",
    "}",
    "",
    "function firstOf(...values: string[]): string {",
    "  for (const v of values) if (v) return v;",
    "  return '';",
    "}",
    "",
    "/** RFC 822 or ISO 8601 to ISO 8601; null for a date that cannot be read rather than a guess. */",
    "function toISODate(value: unknown): string | null {",
    "  const raw = text(value).trim();",
    "  if (!raw) return null;",
    "  const ms = Date.parse(raw);",
    "  if (!isNaN(ms)) return new Date(ms).toISOString();",
    "  const stripped = raw.replace(/\\s+\\([^)]*\\)\\s*$/, '').replace(/\\s+[A-Z]{2,5}$/, ' UTC');",
    "  const retry = Date.parse(stripped);",
    "  return isNaN(retry) ? null : new Date(retry).toISOString();",
    "}",
    "",
    "/** FNV-1a, 32-bit, as 8 lowercase hex characters — the identity ladder's last rung. */",
    "function hashId(input: string): string {",
    "  let h = 0x811c9dc5;",
    "  for (let i = 0; i < input.length; i++) {",
    "    h ^= input.charCodeAt(i);",
    "    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;",
    "  }",
    "  return ('0000000' + h.toString(16)).slice(-8);",
    "}",
    "",
    "/** Atom's `<link>` is a family: `rel=\"alternate\"` is the one a person opens, never `rel=\"self\"`. */",
    "function atomLink(node: unknown): string {",
    "  const links = many(node, 'link');",
    "  const byRel = (rel: string) => links.find((l) => (attr(l, 'rel') || 'alternate').toLowerCase() === rel && attr(l, 'href'));",
    "  const alternate = byRel('alternate');",
    "  if (alternate) return attr(alternate, 'href');",
    "  const firstWithHref = links.find((l) => attr(l, 'href'));",
    "  if (firstWithHref) return attr(firstWithHref, 'href');",
    "  return text(one(node, 'link'));",
    "}",
    "",
    "function itemImage(item: Node): string {",
    "  const group = one(item, 'media:group');",
    "  const search: unknown[] = [item];",
    "  if (group) search.push(group);",
    "  for (const scope of search) {",
    "    for (const thumb of many(scope, 'media:thumbnail')) {",
    "      const url = attr(thumb, 'url');",
    "      if (url) return url;",
    "    }",
    "    for (const media of many(scope, 'media:content')) {",
    "      const medium = attr(media, 'medium').toLowerCase();",
    "      const type = attr(media, 'type').toLowerCase();",
    "      if (medium === 'image' || type.indexOf('image/') === 0) {",
    "        const url = attr(media, 'url');",
    "        if (url) return url;",
    "      }",
    "    }",
    "  }",
    "  const itunes = one(item, 'itunes:image');",
    "  const itunesHref = attr(itunes, 'href') || text(itunes);",
    "  if (itunesHref) return itunesHref;",
    "  for (const enc of many(item, 'enclosure')) {",
    "    if (attr(enc, 'type').toLowerCase().indexOf('image/') === 0) {",
    "      const url = attr(enc, 'url');",
    "      if (url) return url;",
    "    }",
    "  }",
    "  return '';",
    "}",
    "",
    "function itemEnclosure(item: Node): FeedEnclosure | null {",
    "  for (const enc of many(item, 'enclosure')) {",
    "    const url = attr(enc, 'url');",
    "    if (!url) continue;",
    "    const out: FeedEnclosure = { url };",
    "    const type = attr(enc, 'type');",
    "    const length = attr(enc, 'length');",
    "    if (type) out.type = type;",
    "    if (length) out.length = length;",
    "    return out;",
    "  }",
    "  for (const link of many(item, 'link')) {",
    "    if (attr(link, 'rel').toLowerCase() === 'enclosure' && attr(link, 'href')) {",
    "      const out: FeedEnclosure = { url: attr(link, 'href') };",
    "      const type = attr(link, 'type');",
    "      const length = attr(link, 'length');",
    "      if (type) out.type = type;",
    "      if (length) out.length = length;",
    "      return out;",
    "    }",
    "  }",
    "  return null;",
    "}",
    "",
    "function itemTags(item: Node): string[] {",
    "  const out: string[] = [];",
    "  const push = (v: string) => {",
    "    const t = v.trim();",
    "    if (t && out.indexOf(t) === -1) out.push(t);",
    "  };",
    "  for (const cat of many(item, 'category')) push(attr(cat, 'term') || attr(cat, 'label') || text(cat));",
    "  for (const kw of many(item, 'media:keywords')) for (const part of text(kw).split(',')) push(part);",
    "  for (const kw of many(item, 'itunes:keywords')) for (const part of text(kw).split(',')) push(part);",
    "  return out;",
    "}",
    "",
    "function itemAuthor(item: Node): string {",
    "  const atom = one(item, 'author');",
    "  const name = text(one(atom, 'name'));",
    "  if (name) return name;",
    "  return firstOf(text(one(item, 'dc:creator')), text(one(item, 'itunes:author')), text(atom));",
    "}",
    "",
    "function normaliseItem(raw: Node, kind: FeedKind): FeedItem {",
    "  const title = text(one(raw, 'title'));",
    "  const link = kind === 'rss' ? firstOf(text(one(raw, 'link')), atomLink(raw)) : atomLink(raw);",
    "  const published = toISODate(pick(raw, 'pubDate', 'published', 'dc:date', 'date'));",
    "  const updated = toISODate(pick(raw, 'updated', 'lastBuildDate', 'dc:modified'));",
    "  const summary = firstOf(text(one(raw, 'description')), text(one(raw, 'summary')), text(one(raw, 'itunes:summary')));",
    "  const content = firstOf(",
    "    text(one(raw, 'content:encoded')),",
    "    text(one(raw, 'content')),",
    "    text(one(one(raw, 'media:group'), 'media:description')),",
    "    summary",
    "  );",
    "  const id = firstOf(",
    "    text(one(raw, 'guid')),",
    "    text(one(raw, 'id')),",
    "    attr(one(raw, 'guid'), 'isPermaLink') && link ? link : '',",
    "    link,",
    "    // The separator is a NUL byte, not a space: feed.ts's source holds a literal U+0000 between the quotes,",
    "    // which every editor draws as a space. Written as an escape here so the export hashes what the",
    "    // interpreter hashes — FED-002's unique index keys on this id, so a different byte would duplicate rows.",
    "    hashId(title + '\\u0000' + (published || ''))",
    "  );",
    "  return {",
    "    id,",
    "    title,",
    "    link,",
    "    published,",
    "    updated,",
    "    author: itemAuthor(raw),",
    "    summary,",
    "    content,",
    "    image: itemImage(raw),",
    "    enclosure: itemEnclosure(raw),",
    "    tags: itemTags(raw),",
    "    raw",
    "  };",
    "}",
    "",
    "function detectSource(document: string, channel: Node, items: FeedItem[]): FeedSource {",
    "  if (/xmlns:yt=|<yt:channelId>|youtube\\.com\\/(channel|watch)/i.test(document)) return 'youtube';",
    "  if (/reddit\\.com\\/r\\//i.test(document)) return 'reddit';",
    "  if (/xmlns:itunes=/i.test(document) || one(channel, 'itunes:author')) return 'podcast';",
    "  if (items.some((i) => i.enclosure && /^audio\\//i.test(i.enclosure.type || ''))) return 'podcast';",
    "  return 'generic';",
    "}",
    "",
    "function parseFeedText(document: unknown, maxBytes: number): FeedParseResult {",
    "  const parsed = parseXMLText(document, { attributePrefix: '@', alwaysArray: FEED_ARRAY_TAGS, trimValues: true, maxBytes });",
    "  if (parsed.error) return { error: parsed.error };",
    "  const root = parsed.value as Node;",
    "  let kind: FeedKind | undefined;",
    "  let channel: Node = {};",
    "  let rawItems: unknown[] = [];",
    "  const rdf = pick(root, 'rdf:RDF', 'RDF');",
    "  const rss = one(root, 'rss');",
    "  const atom = one(root, 'feed');",
    "  if (isObject(rdf)) {",
    "    kind = 'rdf';",
    "    channel = (one(rdf, 'channel') as Node) || {};",
    "    // RDF puts <item> as a SIBLING of <channel>, not inside it.",
    "    rawItems = many(rdf, 'item');",
    "  } else if (isObject(rss)) {",
    "    kind = 'rss';",
    "    channel = (one(rss, 'channel') as Node) || {};",
    "    rawItems = many(channel, 'item');",
    "  } else if (isObject(atom)) {",
    "    kind = 'atom';",
    "    channel = atom;",
    "    rawItems = many(atom, 'entry');",
    "  }",
    "  if (!kind) {",
    "    return {",
    "      error: {",
    "        code: 'feed/unrecognised',",
    "        message:",
    "          'This XML parsed, but its root is not <rss>, <feed> or <rdf:RDF>, so it is not a feed. ' +",
    "          'Wire it into Parse XML instead and read the shape you actually received'",
    "      }",
    "    };",
    "  }",
    "  const items = rawItems.filter(isObject).map((raw) => normaliseItem(raw as Node, kind as FeedKind));",
    "  const feed: FeedMeta = {",
    "    title: text(one(channel, 'title')),",
    "    link: kind === 'rss' || kind === 'rdf' ? firstOf(text(one(channel, 'link')), atomLink(channel)) : atomLink(channel),",
    "    description: firstOf(text(one(channel, 'description')), text(one(channel, 'subtitle'))),",
    "    updated: toISODate(pick(channel, 'lastBuildDate', 'updated', 'pubDate')),",
    "    kind,",
    "    source: detectSource(typeof document === 'string' ? document.slice(0, 64 * 1024) : '', channel, items)",
    "  };",
    "  return { feed, items };",
    "}",
    "",
    "// ---------------------------------------------------------------------------------------------",
    "// Parse Feed — parsefeed.ts",
    "// ---------------------------------------------------------------------------------------------",
    "",
    "export type ParseFeedOutput =",
    "  | 'items'",
    "  | 'count'",
    "  | 'feedTitle'",
    "  | 'feedLink'",
    "  | 'feedDescription'",
    "  | 'feedUpdated'",
    "  | 'kind'",
    "  | 'source'",
    "  | 'error'",
    "  | 'errorCode';",
    "",
    "interface ParseFeedState {",
    "  items: FeedItem[] | undefined;",
    "  count: number;",
    "  feedTitle: string;",
    "  feedLink: string;",
    "  feedDescription: string;",
    "  feedUpdated: string | undefined;",
    "  kind: string;",
    "  source: string;",
    "  error: string | undefined;",
    "  errorCode: string | undefined;",
    "}",
    "",
    "/** What `initialize` writes: the node before anything has arrived. */",
    "const FEED_UNSET: ParseFeedState = {",
    "  items: undefined,",
    "  count: 0,",
    "  feedTitle: '',",
    "  feedLink: '',",
    "  feedDescription: '',",
    "  feedUpdated: undefined,",
    "  kind: '',",
    "  source: '',",
    "  error: undefined,",
    "  errorCode: undefined",
    "};",
    "",
    "let lastFeed: { text: unknown; maxBytes: unknown; state: ParseFeedState } | undefined;",
    "",
    "function parseFeedState(text: unknown, maxBytes: unknown): ParseFeedState {",
    "  if (lastFeed && lastFeed.text === text && lastFeed.maxBytes === maxBytes) return lastFeed.state;",
    "  let state: ParseFeedState;",
    "  if (text === undefined || text === null) {",
    "    state = FEED_UNSET;",
    "  } else {",
    "    const result = parseFeedText(text, maxBytesOf(maxBytes));",
    "    if (result.error) {",
    "      state = { ...FEED_UNSET, error: result.error.message, errorCode: result.error.code };",
    "    } else {",
    "      const items = result.items || [];",
    "      const feed = result.feed;",
    "      state = {",
    "        items,",
    "        count: items.length,",
    "        feedTitle: (feed && feed.title) || '',",
    "        feedLink: (feed && feed.link) || '',",
    "        feedDescription: (feed && feed.description) || '',",
    "        feedUpdated: (feed && feed.updated) || undefined,",
    "        kind: (feed && feed.kind) || '',",
    "        source: (feed && feed.source) || '',",
    "        error: undefined,",
    "        errorCode: undefined",
    "      };",
    "    }",
    "  }",
    "  lastFeed = { text, maxBytes, state };",
    "  return state;",
    "}",
    "",
    "/**",
    " * `Parse Feed` — RSS 2.0, Atom 1.0 or RDF in; one list of items out, each with Id, Title, Link, Published,",
    " * Updated, Author, Summary, Content, Image, Enclosure, Tags and Raw; the feed's own title, link,",
    " * description and kind beside it.",
    " */",
    "export function parseFeed(text: unknown, maxBytes: unknown, output: 'items'): any[] | undefined;",
    "export function parseFeed(text: unknown, maxBytes: unknown, output: 'count'): number;",
    "export function parseFeed(text: unknown, maxBytes: unknown, output: 'feedTitle' | 'feedLink' | 'feedDescription' | 'kind' | 'source'): string;",
    "export function parseFeed(text: unknown, maxBytes: unknown, output: 'feedUpdated' | 'error' | 'errorCode'): string | undefined;",
    "export function parseFeed(text: unknown, maxBytes: unknown, output: ParseFeedOutput): unknown {",
    "  return parseFeedState(text, maxBytes)[output];",
    "}"
  ].join('\n');
}
