/**
 * GAM-013 (P88) — `Repeat`, emitted into the app: `src/lib/repeat.ts`, the node transcribed from
 * `noodl-viewer-react/src/nodes/std-library/repeat.ts`, with the outcome contract of `noodl-runtime/src/node.ts`'s
 * `reportOutcome` (a Failure raises on `./errors` before its pulse; Completed fires after every outcome).
 *
 * The seventh member of the streaming table (EXP-011 §58, §64-§66), because its shape is that table's exactly: two
 * Actions as verbs on a handle (`start()` / `stop()`), Tick and the outcome trio as listeners, Count a live getter, the
 * Interval a config option read live, and the unmount cleanup as the node's delete listener. Delay (`timer.ts`, §39) is
 * the other translated clock, and it could not carry this node: it publishes no value, and its callbacks are compiled
 * per verb where Tick belongs to the node.
 *
 * One module per feature: an app that delays does not ship a beat, and an app with a beat does not ship `timer.ts`.
 *
 * Kept as a quoted line array like the other libs: the specs pin lines of it, and mutation arms anchor on them.
 * Generated from a plain source (repeat-lib-source.ts + gen-repeatlib.py, GAM-013's scratchpad) — regenerate, never
 * hand-edit the array.
 */

/** Where the module lands in the exported app. */
export const REPEAT_LIB_PATH = 'src/lib/repeat.ts';

export function repeatLibSource(): string {
  return [
    '//',
    '// Repeat, transcribed from the interpreter it has to agree with:',
    '// noodl-viewer-react/src/nodes/std-library/repeat.ts (the node: Start and Stop, the beat, the outcomes) over',
    '// noodl-runtime/src/node.ts\'s reportOutcome (a Failure raises before its pulse; Completed fires after every outcome).',
    '//',
    '// useRepeat(source, options, listeners): one beat per mount. `start()` / `stop()` are the two Actions, Tick and the',
    '// outcome trio are the listeners, Count is a live getter on the handle. The Interval is the one option, read at Start',
    '// and again at every tick, so a change takes effect from the next tick. Unmounting stops the beat: the node\'s delete',
    '// listener, which the runtime runs on delete, on unmount and on leaving the page.',
    '//',
    '// The beat runs on setTimeout where the interpreter\'s runs on the frame loop (context.timerScheduler). A tick is due',
    '// at a time, and fires at the first moment at or after it either way; nothing an author wires can tell the two apart',
    '// beyond the frame the interpreter rounds a Start to.',
    '//',
    '',
    'import { useEffect, useReducer, useRef } from \'react\';',
    '',
    'import { raiseAppError } from \'./errors\';',
    '',
    '/** The failure a Start reports when its Interval is not a number of milliseconds above zero. */',
    'export const REPEAT_ERROR_INTERVAL_NOT_POSITIVE = \'repeat/interval-not-positive\';',
    '',
    '/** Where the node sits: the provenance a raise carries. */',
    'export interface RepeatSource {',
    '  /** The authored label, or the node\'s display name. */',
    '  label: string;',
    '  /** The node\'s graph id. */',
    '  nodeId: string;',
    '  /** The component it sits in, \'/Pages/Home\'. */',
    '  componentName: string;',
    '}',
    '',
    '/** The node\'s one value input. Undefined means no setter ran, and the Interval keeps its last value. */',
    'export interface RepeatOptions {',
    '  interval?: unknown;',
    '}',
    '',
    '/** The signal outputs, in the node\'s declaration order. */',
    'export interface RepeatListeners {',
    '  tick?: () => void;',
    '  done?: () => void;',
    '  completed?: () => void;',
    '  unchanged?: () => void;',
    '  failure?: () => void;',
    '}',
    '',
    'export interface RepeatHandle {',
    '  /** The Start action: Done when a beat began, Unchanged while one runs, Failure on an unusable Interval. */',
    '  start(): void;',
    '  /** The Stop action: Done when a beat was stopped, Unchanged when none ran. */',
    '  stop(): void;',
    '  /** How many times Tick has fired since the last Start. Start resets it; Stop keeps it. */',
    '  readonly count: number;',
    '}',
    '',
    '/** The clock the beat runs on. The browser\'s by default; a test hands its own. */',
    'export interface RepeatClock {',
    '  now(): number;',
    '  setTimeout(fn: () => void, ms: number): unknown;',
    '  clearTimeout(handle: unknown): void;',
    '}',
    '',
    'const browserClock: RepeatClock = {',
    '  now: () => (typeof performance !== \'undefined\' ? performance.now() : Date.now()),',
    '  setTimeout: (fn, ms) => setTimeout(fn, ms),',
    '  clearTimeout: (handle) => clearTimeout(handle as ReturnType<typeof setTimeout>)',
    '};',
    '',
    '/** isUsableInterval: a finite number of milliseconds above zero. */',
    'export function isUsableInterval(value: unknown): value is number {',
    '  return typeof value === \'number\' && Number.isFinite(value) && value > 0;',
    '}',
    '',
    '/** One node\'s beat, outside React: the node\'s `_internal` and its three handlers. The hook below hosts one. */',
    'export interface RepeatBeat {',
    '  readonly count: number;',
    '  readonly running: boolean;',
    '  /** The Interval input\'s setter: stores what arrived. Read at Start and at every tick. */',
    '  setIntervalInput(value: unknown): void;',
    '  setListeners(on: RepeatListeners): void;',
    '  start(): void;',
    '  stop(): void;',
    '  /** The delete listener: the beat stops, and no outcome fires. */',
    '  dispose(): void;',
    '}',
    '',
    'interface RepeatState {',
    '  source: RepeatSource;',
    '  clock: RepeatClock;',
    '  rerender: () => void;',
    '  listeners: RepeatListeners;',
    '  running: boolean;',
    '  count: number;',
    '  /** The Interval input as last set, in milliseconds. */',
    '  interval: unknown;',
    '  /** The interval the running beat uses: the last valid one. */',
    '  beat: number;',
    '  /** The time the next tick is due. */',
    '  nextAt: number;',
    '  /** The one pending timeout. Scheduling again replaces it, as the scheduler keeps one timer per node. */',
    '  timer: unknown;',
    '}',
    '',
    'function reportOutcome(s: RepeatState, outcome: \'done\' | \'unchanged\' | \'failure\', failure?: { code: string; message: string }): void {',
    '  if (outcome === \'failure\' && failure !== undefined) {',
    '    raiseAppError({ code: failure.code, message: failure.message, nodeId: s.source.nodeId, nodeType: \'Repeat\', componentName: s.source.componentName });',
    '  }',
    '  s.listeners[outcome]?.();',
    '  s.listeners.completed?.();',
    '}',
    '',
    'function cancel(s: RepeatState): void {',
    '  if (s.timer !== null) {',
    '    s.clock.clearTimeout(s.timer);',
    '    s.timer = null;',
    '  }',
    '}',
    '',
    'function schedule(s: RepeatState, ms: number): void {',
    '  cancel(s);',
    '  s.timer = s.clock.setTimeout(() => {',
    '    s.timer = null;',
    '    tick(s);',
    '  }, ms);',
    '}',
    '',
    '/** _tick: Count, then Tick, then the next tick on the beat. */',
    'function tick(s: RepeatState): void {',
    '  if (!s.running) return;',
    '',
    '  s.count += 1;',
    '  s.rerender();',
    '  s.listeners.tick?.();',
    '',
    '  // A Stop wired from Tick has already run by here.',
    '  if (!s.running) return;',
    '',
    '  if (isUsableInterval(s.interval)) s.beat = s.interval;',
    '  const now = s.clock.now();',
    '  s.nextAt += s.beat;',
    '  if (s.nextAt <= now) {',
    '    // Ticks missed while the tab was throttled are skipped, not replayed, and the beat keeps its phase.',
    '    s.nextAt += Math.ceil((now - s.nextAt) / s.beat + Number.EPSILON) * s.beat;',
    '  }',
    '  schedule(s, s.nextAt - now);',
    '}',
    '',
    '/** createRepeatBeat: initialize. Running false, Count 0, Interval 1000 (the port\'s default). */',
    'export function createRepeatBeat(source: RepeatSource, clock: RepeatClock = browserClock, rerender: () => void = () => undefined): RepeatBeat {',
    '  const s: RepeatState = {',
    '    source,',
    '    clock,',
    '    rerender,',
    '    listeners: {},',
    '    running: false,',
    '    count: 0,',
    '    interval: 1000,',
    '    beat: 1000,',
    '    nextAt: 0,',
    '    timer: null',
    '  };',
    '  return {',
    '    get count() {',
    '      return s.count;',
    '    },',
    '    get running() {',
    '      return s.running;',
    '    },',
    '    setIntervalInput(value: unknown) {',
    '      s.interval = value;',
    '    },',
    '    setListeners(on: RepeatListeners) {',
    '      s.listeners = on;',
    '    },',
    '    start() {',
    '      // The guard is the node\'s own flag, set the moment Start is handled, so two Starts in one turn begin one beat.',
    '      if (s.running) {',
    '        reportOutcome(s, \'unchanged\');',
    '        return;',
    '      }',
    '      if (!isUsableInterval(s.interval)) {',
    '        reportOutcome(s, \'failure\', {',
    '          code: REPEAT_ERROR_INTERVAL_NOT_POSITIVE,',
    '          message: `Interval is ${String(s.interval)}, and Repeat needs a number of milliseconds above zero`',
    '        });',
    '        return;',
    '      }',
    '',
    '      s.running = true;',
    '      s.beat = s.interval;',
    '      s.nextAt = s.clock.now() + s.beat;',
    '      if (s.count !== 0) {',
    '        s.count = 0;',
    '        s.rerender();',
    '      }',
    '      schedule(s, s.beat);',
    '      reportOutcome(s, \'done\');',
    '    },',
    '    stop() {',
    '      if (!s.running) {',
    '        reportOutcome(s, \'unchanged\');',
    '        return;',
    '      }',
    '      s.running = false;',
    '      cancel(s);',
    '      reportOutcome(s, \'done\');',
    '    },',
    '    dispose() {',
    '      s.running = false;',
    '      cancel(s);',
    '    }',
    '  };',
    '}',
    '',
    '/**',
    ' * useRepeat: one beat per mount. The Interval and the listeners are re-read every render; the effect\'s cleanup is the',
    ' * node\'s delete listener. StrictMode runs the mount twice in development: the cleanup between stops the first beat,',
    ' * and a Start fired from the second mount begins again.',
    ' */',
    'export function useRepeat(source: RepeatSource, options: RepeatOptions = {}, on: RepeatListeners = {}, clock: RepeatClock = browserClock): RepeatHandle {',
    '  const [, publish] = useReducer((n: number) => n + 1, 0);',
    '  const beatRef = useRef<RepeatBeat | null>(null);',
    '  const handleRef = useRef<RepeatHandle | null>(null);',
    '  if (beatRef.current === null || handleRef.current === null) {',
    '    const created = createRepeatBeat(source, clock, () => publish());',
    '    beatRef.current = created;',
    '    handleRef.current = {',
    '      start: () => created.start(),',
    '      stop: () => created.stop(),',
    '      get count() {',
    '        return created.count;',
    '      }',
    '    };',
    '  }',
    '  const beat = beatRef.current;',
    '  // The setter runs on every render that delivers a value; an undefined option ran no setter.',
    '  if (options.interval !== undefined) beat.setIntervalInput(options.interval);',
    '  beat.setListeners(on);',
    '',
    '  useEffect(() => {',
    '    return () => {',
    '      beat.dispose();',
    '    };',
    '    // eslint-disable-next-line react-hooks/exhaustive-deps -- the beat is created once',
    '  }, []);',
    '',
    '  return handleRef.current;',
    '}'
  ].join('\n');
}
