/**
 * `src/lib/states.ts` — the `States` node, emitted into the app (EXP-011 §49).
 *
 * {@link ./animateLib.ts}'s shape, one module over, and a module of its own because an app that
 * fades a number should not ship a state machine. It imports `./animate` for the run engine, the
 * bezier solver and the linear curve.
 *
 * It is a transcription of `noodl-viewer-react/src/nodes/std-library/states.ts`:
 *
 * - **Requests are queued per pass and drained after it** (`scheduleGoToState` over
 *   `scheduleAfterInputsHaveUpdated`): a request for where the pass is already heading answers
 *   Unchanged at once; otherwise all but the last request are *settled immediately* and the last
 *   one animates. The drain here is a microtask — the handler that asked is the pass.
 * - **`goToState`**: a falsy state is the first state; the current state is Unchanged; a name not
 *   in the list is Failure, with the node's own `Error` text (`nearestName` transcribed for the
 *   "Did you mean" clause); the first ever request jumps (no State Changed); after that booleans and
 *   strings jump, numbers and colours tween along `transition-<state>-<value>`, else
 *   `transitiondef-<state>`, else `{[0, 0, 0.58, 1], 300, 0}`, and settle at once when both are 0,
 *   when Use Transitions is off, or when the state is one the pass only passed through. `State`,
 *   `At <state>` and State Changed move at the request; `Has Reached <state>` at the tween's end
 *   (at once when there is none); Done after State Changed.
 * - **Colours** go through `resolveColor`, then `readColor` (the viewer's `color-reader.ts`,
 *   transcribed), interpolate per channel with `Math.floor`, come back as `rgbaToHex`, and land on
 *   the value the state names. Before GAM-006 (P88) the interpreter read every colour as hex, so a
 *   `var(--token)` tweened through `#0aNaNNaNNaN`; it now reads the token off the document, as this
 *   module always did. A colour unreadable at either end holds the colour on screen until the end,
 *   in both worlds. The one departure left: this `resolveColor` also resolves a named colour
 *   (`red`) through a probe element, so here it glides where the interpreter holds.
 * - **A colour with a per-value delay holds the colour on screen for the delay.** Before GAM-006
 *   (P88) both worlds published the tween's parsed RGBA array there (`currentValues[v] =
 *   this.startValues[v]`), which no style sink accepts. Both now publish the start colour string.
 * - **Boot** (`states`'s setter, then an authored `currentState`): the node jumps to the first
 *   state, and an authored State that is not the first is a queued request — so it *animates* from
 *   the first state at boot and fires State Changed. Reproduced.
 */

/** Where the module lands in the exported app. */
export const STATES_LIB_PATH = 'src/lib/states.ts';

/** The exported helpers a component imports. Sorted — the import list is sorted too. */
export const STATES_HELPERS = ['defineStates', 'useStates'] as const;

/** The value types this slice translates — `textStyle` is refused by name. */
export const STATES_VALUE_TYPES = ['number', 'string', 'boolean', 'color'] as const;
export type StatesValueType = (typeof STATES_VALUE_TYPES)[number];

/** The interpreter's default transition, `goToState`'s own literal. */
export const DEFAULT_TRANSITION = { curve: [0.0, 0.0, 0.58, 1.0], dur: 300, delay: 0 } as const;

/**
 * The module's source — a plain string, for `dateLib.ts`'s stated reason.
 */
export function statesLibSource(): string {
  return [
    '//',
    '// The States node, transcribed from the interpreter it has to agree with:',
    '// noodl-viewer-react/src/nodes/std-library/states.ts over the run engine in ./animate.',
    '//',
    '// Requests are queued per handler and drained after it; all but the last settle at once and the last',
    '// animates. A falsy state is the first state, the current state is Unchanged, an unknown name is a',
    '// Failure with the node\'s own Error text. Numbers and colours tween along the state\'s curve; booleans',
    '// and strings jump. State, At <state> and State Changed move at the request; Has Reached <state> when',
    '// the tween ends. The first state is entered silently, as the node does.',
    '//',
    '',
    "import { useEffect, useRef, useState } from 'react';",
    '',
    "import { Run, createRun, cubicBezier, eases, startRun, stopRun } from './animate';",
    '',
    '// ---- the definition a component writes ------------------------------------------------------------',
    '',
    'export interface Curve {',
    '  curve: readonly number[];',
    '  dur: number;',
    '  delay: number;',
    '}',
    '',
    "export type ValueType = 'number' | 'string' | 'boolean' | 'color';",
    '',
    'export interface ValueDef<T> {',
    '  type: ValueType;',
    '  /** `value-<state>-<name>`, by state. */',
    '  byState: Record<string, T>;',
    '  /** `transition-<state>-<name>`, by state — absent where the state\'s default applies. */',
    '  transitions?: Record<string, Curve>;',
    '}',
    '',
    'export interface StatesDef<V extends Record<string, ValueDef<unknown>>> {',
    '  states: readonly string[];',
    '  values: V;',
    '  /** `transitiondef-<state>`, by state. */',
    '  transitions?: Record<string, Curve>;',
    '  useTransitions: boolean;',
    '}',
    '',
    'export type ValuesOf<V> = { [K in keyof V]: V[K] extends ValueDef<infer T> ? T : never };',
    '',
    '/** What the component reads: the state, every value, and the last Error. */',
    'export interface StatesSnapshot<V extends Record<string, ValueDef<unknown>>> {',
    '  state: string;',
    '  values: ValuesOf<V>;',
    '  error: string | undefined;',
    '}',
    '',
    '/** The node\'s signal outputs, as callbacks the component passes once. */',
    'export interface StatesListeners {',
    '  stateChanged?: () => void;',
    '  reached?: Record<string, () => void>;',
    '  done?: () => void;',
    '  unchanged?: () => void;',
    '  failure?: () => void;',
    '}',
    '',
    '/** Identity, typed: it fixes `V` so `values.<name>` reads with the declared type. */',
    'export function defineStates<V extends Record<string, ValueDef<unknown>>>(def: StatesDef<V>): StatesDef<V> {',
    '  return def;',
    '}',
    '',
    '// ---- colours: setRGBA / rgbaToHex / resolveColor -----------------------------------------------------',
    '',
    'type RGBA = [number, number, number, number];',
    '',
    '/** `false` for a colour `readColor` cannot read; `transparent` and empty zero the alpha. */',
    'function setRGBA(result: RGBA, color: string): boolean {',
    "  if (color === 'transparent' || !color) {",
    '    result[3] = 0;',
    '    return true;',
    '  }',
    '  const rgba = readColor(color);',
    '  if (!rgba) return false;',
    '  result[0] = rgba[0];',
    '  result[1] = rgba[1];',
    '  result[2] = rgba[2];',
    '  result[3] = rgba[3];',
    '  return true;',
    '}',
    '',
    '/**',
    ' * A colour as four channels, or `null` when this notation cannot be read: `var(--token)` off the document',
    ' * (then its own fallback), `#RGB`, `#RRGGBB[AA]`, `rgb()`, `rgba()`. Transcribed from the viewer\'s',
    ' * `color-reader.ts`, which the interpreter\'s States node reads through (GAM-006).',
    ' */',
    'function readColor(value: unknown, depth = 0): RGBA | null {',
    "  if (typeof value !== 'string') return null;",
    '  const text = value.trim();',
    '  if (!text) return null;',
    '  const asVar = /^var\\(\\s*(--[^,)\\s]+)\\s*(?:,([\\s\\S]*))?\\)$/.exec(text);',
    '  if (asVar) {',
    '    if (depth >= 8) return null;',
    "    let resolved = '';",
    "    if (typeof document !== 'undefined' && document.documentElement && typeof getComputedStyle === 'function') {",
    '      try {',
    '        resolved = getComputedStyle(document.documentElement).getPropertyValue(asVar[1]).trim();',
    '      } catch (e) {',
    "        resolved = '';",
    '      }',
    '    }',
    '    if (resolved) return readColor(resolved, depth + 1);',
    '    if (asVar[2] !== undefined) return readColor(asVar[2], depth + 1);',
    '    return null;',
    '  }',
    '  const clamp = (n: number): number => Math.max(0, Math.min(255, n));',
    '  const short = /^#([0-9a-f])([0-9a-f])([0-9a-f])$/i.exec(text);',
    '  if (short) return [parseInt(short[1] + short[1], 16), parseInt(short[2] + short[2], 16), parseInt(short[3] + short[3], 16), 255];',
    '  const long = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})?/i.exec(text);',
    '  if (long) return [parseInt(long[1], 16), parseInt(long[2], 16), parseInt(long[3], 16), long[4] === undefined ? 255 : parseInt(long[4], 16)];',
    '  const fn = /^rgba?\\(\\s*([\\d.]+)[\\s,]+([\\d.]+)[\\s,]+([\\d.]+)(?:[\\s,\\/]+([\\d.]+)(%?))?/i.exec(text);',
    '  if (fn) {',
    "    const alpha = fn[4] === undefined ? 255 : clamp(Math.round((fn[5] === '%' ? Number(fn[4]) / 100 : Number(fn[4])) * 255));",
    '    return [clamp(Math.round(Number(fn[1]))), clamp(Math.round(Number(fn[2]))), clamp(Math.round(Number(fn[3]))), alpha];',
    '  }',
    '  return null;',
    '}',
    '',
    'function componentToHex(c: number): string {',
    '  const hex = c.toString(16);',
    "  return hex.length == 1 ? '0' + hex : hex;",
    '}',
    '',
    'function rgbaToHex(rgba: RGBA): string {',
    "  return '#' + componentToHex(rgba[0]) + componentToHex(rgba[1]) + componentToHex(rgba[2]) + componentToHex(rgba[3]);",
    '}',
    '',
    '/**',
    " * The interpreter's `resolveColor` is a lookup in a table no v2 project carries, so a token reaches",
    " * `setRGBA` unresolved there. Here a `var(--token)` is read off the document, and any other non-hex",
    ' * colour is resolved through a probe element; with no document the string passes through unchanged,',
    " * which is the interpreter's own answer.",
    ' */',
    'export function resolveColor(color: string): string {',
    "  if (typeof document === 'undefined' || typeof getComputedStyle !== 'function') return color;",
    '  let value = String(color).trim();',
    '  const token = /^var\\((--[^,)]+)(?:,\\s*([^)]*))?\\)$/.exec(value);',
    '  if (token) {',
    '    const resolved = getComputedStyle(document.documentElement).getPropertyValue(token[1]).trim();',
    "    value = resolved || (token[2] ?? '').trim() || value;",
    '  }',
    "  if (value.startsWith('#') || value === 'transparent' || value === '') return value;",
    "  const probe = document.createElement('span');",
    '  probe.style.color = value;',
    '  document.body.appendChild(probe);',
    '  const computed = getComputedStyle(probe).color;',
    '  probe.remove();',
    '  const rgb = /^rgba?\\((\\d+),\\s*(\\d+),\\s*(\\d+)(?:,\\s*([\\d.]+))?\\)$/.exec(computed);',
    '  if (!rgb) return value;',
    '  const alpha = rgb[4] === undefined ? 1 : Number(rgb[4]);',
    "  return rgbaToHex([Number(rgb[1]), Number(rgb[2]), Number(rgb[3]), Math.round(alpha * 255)]).slice(0, alpha === 1 ? 7 : 9);",
    '}',
    '',
    '// ---- diagnostics.ts — nearestName, for the Error text -------------------------------------------------',
    '',
    'function editDistance(a: string, b: string): number {',
    '  if (a === b) return 0;',
    '  if (!a.length) return b.length;',
    '  if (!b.length) return a.length;',
    '  let previous = new Array<number>(b.length + 1);',
    '  let current = new Array<number>(b.length + 1);',
    '  for (let j = 0; j <= b.length; j++) previous[j] = j;',
    '  for (let i = 1; i <= a.length; i++) {',
    '    current[0] = i;',
    '    for (let j = 1; j <= b.length; j++) {',
    '      const substitution = previous[j - 1] + (a.charCodeAt(i - 1) === b.charCodeAt(j - 1) ? 0 : 1);',
    '      current[j] = Math.min(current[j - 1] + 1, previous[j] + 1, substitution);',
    '    }',
    '    const swap = previous;',
    '    previous = current;',
    '    current = swap;',
    '  }',
    '  return previous[b.length];',
    '}',
    '',
    'const MAX_CANDIDATES = 64;',
    '',
    'function nearestName(name: string, candidates: readonly string[]): string | undefined {',
    "  if (typeof name !== 'string' || !name.length || !candidates || !candidates.length) return undefined;",
    '  if (candidates.length > MAX_CANDIDATES) return undefined;',
    '  const normalised = name.trim().toLowerCase();',
    '  for (let i = 0; i < candidates.length; i++) {',
    '    const candidate = candidates[i];',
    "    if (typeof candidate === 'string' && candidate.trim().toLowerCase() === normalised) return candidate;",
    '  }',
    '  const budget = normalised.length <= 4 ? 1 : 2;',
    '  let best: string | undefined;',
    '  let bestDistance = budget + 1;',
    '  for (let i = 0; i < candidates.length; i++) {',
    '    const candidate = candidates[i];',
    "    if (typeof candidate !== 'string') continue;",
    '    const distance = editDistance(normalised, candidate.trim().toLowerCase());',
    '    if (distance < bestDistance) {',
    '      bestDistance = distance;',
    '      best = candidate;',
    '    } else if (distance === bestDistance) {',
    '      best = undefined;',
    '    }',
    '  }',
    '  return bestDistance <= budget ? best : undefined;',
    '}',
    '',
    '// ---- the machine: states.ts `_internal` and its prototype extensions --------------------------------',
    '',
    'interface Tween {',
    '  curves: Record<string, Curve>;',
    '  funcs: Record<string, (x: number) => number>;',
    '  start: Record<string, number | RGBA>;',
    '  target: Record<string, number | RGBA>;',
    "  kinds: Record<string, 'number' | 'color'>;",
    '  /** A colour unreadable at either end, which holds instead of tweening. */',
    '  unreadable: Record<string, boolean>;',
    '}',
    '',
    'export interface StatesMachine {',
    '  def: StatesDef<Record<string, ValueDef<unknown>>>;',
    '  state: string | undefined;',
    '  values: Record<string, unknown>;',
    '  startValues: Record<string, unknown>;',
    '  initialised: boolean;',
    '  error: string | undefined;',
    '  queue: Array<{ state: unknown; invoked: boolean }>;',
    '  scheduled: boolean;',
    '  run: Run;',
    '  tween: Tween | null;',
    '  publish: () => void;',
    '  listeners: () => StatesListeners;',
    '}',
    '',
    'const DEFAULT_TRANSITION: Curve = { curve: [0.0, 0.0, 0.58, 1.0], dur: 300, delay: 0 };',
    '',
    '/** `initialize` + the `states` setter\'s first request + an authored State: jumps to the first state, then queues the authored one. */',
    'export function createStatesMachine(',
    '  def: StatesDef<Record<string, ValueDef<unknown>>>,',
    '  start: string | undefined,',
    '  listeners: () => StatesListeners,',
    '  publish: () => void = () => undefined',
    '): StatesMachine {',
    '  const m: StatesMachine = {',
    '    def,',
    '    state: undefined,',
    '    values: {},',
    '    startValues: {},',
    '    initialised: false,',
    '    error: undefined,',
    '    queue: [],',
    '    scheduled: false,',
    '    run: createRun(300, 0),',
    '    tween: null,',
    '    publish,',
    '    listeners',
    '  };',
    '  m.run.onStart = () => onTweenStart(m);',
    '  m.run.onRunning = (t) => onTweenRunning(m, t);',
    '  m.run.onFinish = () => {',
    '    const reached = m.listeners().reached;',
    '    if (m.state !== undefined) reached?.[m.state]?.();',
    '  };',
    '  jumpToState(m, undefined);',
    '  if (start !== undefined && start !== m.state) scheduleGoToState(m, start, false);',
    '  return m;',
    '}',
    '',
    'function valueNames(m: StatesMachine): string[] {',
    '  return Object.keys(m.def.values);',
    '}',
    '',
    'function jumpToState(m: StatesMachine, state: string | undefined): void {',
    '  const states = m.def.states;',
    '  if (!states.length) return;',
    '  if (!state) state = states[0];',
    '  if (m.state === state) return;',
    '  stopRun(m.run);',
    '  for (const v of valueNames(m)) m.values[v] = m.def.values[v].byState[state] || 0;',
    '  m.state = state;',
    '  m.publish();',
    '  // Entering the very first state is the node arriving where it starts, not a transition.',
    '  if (m.initialised) m.listeners().stateChanged?.();',
    '  m.initialised = true;',
    '}',
    '',
    'function failUnknownState(m: StatesMachine, state: string, invoked: boolean): void {',
    '  const states = m.def.states;',
    '  const suggestion = nearestName(state, states);',
    '  const message =',
    '    \'Cannot go to state "\' +',
    '    state +',
    '    \'" — this node has no such state. Its states are: \' +',
    "    (states.length > 0 ? states.join(', ') : '(none defined)') +",
    "    '.' +",
    '    (suggestion ? \' Did you mean "\' + suggestion + \'"?\' : \'\');',
    '  m.error = message;',
    '  m.publish();',
    '  // One port doing two jobs: the invocation\'s outcome, and the setter routes\' announcement. Pulsed once.',
    '  void invoked;',
    '  m.listeners().failure?.();',
    '}',
    '',
    '/**',
    ' * `goToState`. `settleImmediately` is a state the pass only passed through; `invoked` says a Toggle or a',
    ' * To <state> asked (the setter routes carry no outcome — `currentState`, the boot request).',
    ' */',
    'function goToState(m: StatesMachine, requested: unknown, settleImmediately: boolean, invoked: boolean): void {',
    '  const states = m.def.states;',
    '  if (!states.length) return;',
    '  const state = requested ? String(requested) : states[0];',
    '  if (m.state === state) {',
    '    if (invoked) m.listeners().unchanged?.();',
    '    return;',
    '  }',
    '  if (states.indexOf(state) === -1) {',
    '    failUnknownState(m, state, invoked);',
    '    return;',
    '  }',
    '  if (!m.initialised) {',
    '    jumpToState(m, state);',
    '    if (invoked) m.listeners().done?.();',
    '    return;',
    '  }',
    '  let delay = 0;',
    '  let dur = 0;',
    '  const curves: Record<string, Curve> = {};',
    '  const funcs: Record<string, (x: number) => number> = {};',
    '  for (const v of valueNames(m)) {',
    '    const def = m.def.values[v];',
    '    m.startValues[v] = m.values[v];',
    "    if (def.type === 'boolean') {",
    '      const b = def.byState[state];',
    '      m.values[v] = b === undefined ? false : !!b;',
    "    } else if (def.type === 'string') {",
    '      m.values[v] = def.byState[state];',
    '    } else {',
    '      const curve = def.transitions?.[state] ?? m.def.transitions?.[state] ?? DEFAULT_TRANSITION;',
    '      if ((curve.dur === 0 && curve.delay === 0) || !m.def.useTransitions || settleImmediately) {',
    '        m.values[v] = def.byState[state];',
    '      } else {',
    '        funcs[v] = cubicBezier(curve.curve);',
    '        curves[v] = curve;',
    '        delay = Math.min(delay, curve.delay);',
    '        dur = Math.max(dur, curve.dur + curve.delay);',
    '      }',
    '    }',
    '  }',
    '  if (dur > 0 || delay > 0) {',
    '    m.tween = { curves, funcs, start: {}, target: {}, kinds: {}, unreadable: {} };',
    '    m.run.duration = dur;',
    '    m.run.delay = delay;',
    '    startRun(m.run);',
    '  }',
    '  m.state = state;',
    '  m.publish();',
    '  const listeners = m.listeners();',
    '  listeners.stateChanged?.();',
    '  if (dur == 0 && delay == 0) listeners.reached?.[state]?.();',
    '  // After State Changed and any Has Reached — a transition still animating has already moved the node.',
    '  if (invoked) listeners.done?.();',
    '}',
    '',
    '/** The timer\'s `onStart`: start and target values for every tweening value, colours parsed to RGBA. */',
    'function onTweenStart(m: StatesMachine): void {',
    '  const tween = m.tween;',
    '  if (tween === null || m.state === undefined) return;',
    '  for (const v in tween.curves) {',
    '    const def = m.def.values[v];',
    '    const target = def.byState[m.state];',
    "    if (def.type === 'color') {",
    "      tween.kinds[v] = 'color';",
    '      const start: RGBA = [0, 0, 0, 255];',
    "      const fromRead = setRGBA(start, resolveColor((m.startValues[v] as string) || '#000000'));",
    '      tween.start[v] = start;',
    '      const end: RGBA = [0, 0, 0, 255];',
    "      const toRead = setRGBA(end, resolveColor((target as string) || '#000000'));",
    '      tween.target[v] = end;',
    '      tween.unreadable[v] = !fromRead || !toRead;',
    '    } else {',
    "      tween.kinds[v] = 'number';",
    '      tween.start[v] = m.startValues[v] as number;',
    '      tween.target[v] = (target as number) || 0;',
    '    }',
    '  }',
    '}',
    '',
    '/** The timer\'s `onRunning`: per value, before its delay the start value, after its span the target, between them the curve. */',
    'function onTweenRunning(m: StatesMachine, t: number): void {',
    '  const tween = m.tween;',
    '  if (tween === null) return;',
    '  const ms = t * m.run.duration;',
    '  const rgba2: RGBA = [0, 0, 0, 255];',
    '  for (const v in tween.curves) {',
    '    const c = tween.curves[v];',
    "    // GAM-006 (a), as `states.ts` does: a colour the reader could not read has nothing to tween between.",
    "    const holding = ms < c.delay || (tween.kinds[v] === 'color' && tween.unreadable[v] && ms < c.delay + c.dur);",
    '    if (holding) {',
    "      // GAM-006, as `states.ts` does: a waiting colour (its delay, or unreadable) holds the colour already on screen,",
    "      // not the RGBA array the tween parsed it into. A start that was never a colour string falls back to the tween's hex.",
    '      const onScreen = m.startValues[v];',
    "      m.values[v] = tween.kinds[v] !== 'color'",
    '        ? tween.start[v]',
    "        : typeof onScreen === 'string' && onScreen !== ''",
    '          ? onScreen',
    '          : rgbaToHex(tween.start[v] as RGBA);',
    '    } else if (ms >= c.delay + c.dur) {',
    "      // GAM-006 (b), as `states.ts` does: a colour lands on the value its state names, so a token",
    "      // the tween could not read still arrives. A state that names no colour ends where the tween does.",
    "      const authored = m.state === undefined ? undefined : m.def.values[v].byState[m.state];",
    "      m.values[v] = tween.kinds[v] !== 'color'",
    '        ? tween.target[v]',
    "        : authored !== undefined && authored !== null && authored !== ''",
    '          ? authored',
    '          : rgbaToHex(tween.target[v] as RGBA);',
    '    } else {',
    '      const _t = tween.funcs[v]((ms - c.delay) / c.dur);',
    "      if (tween.kinds[v] === 'number') {",
    '        // Numbers, since the values might be strings, which can cause NaN.',
    '        m.values[v] = eases.linear(Number(tween.start[v]), Number(tween.target[v]), _t);',
    '      } else {',
    '        const rgba0 = tween.start[v] as RGBA;',
    '        const rgba1 = tween.target[v] as RGBA;',
    '        rgba2[0] = Math.floor(eases.linear(rgba0[0], rgba1[0], _t));',
    '        rgba2[1] = Math.floor(eases.linear(rgba0[1], rgba1[1], _t));',
    '        rgba2[2] = Math.floor(eases.linear(rgba0[2], rgba1[2], _t));',
    '        rgba2[3] = Math.floor(eases.linear(rgba0[3], rgba1[3], _t));',
    '        m.values[v] = rgbaToHex(rgba2);',
    '      }',
    '    }',
    '  }',
    '  m.publish();',
    '}',
    '',
    '/**',
    ' * `scheduleGoToState`: a request for where the pass is already heading is Unchanged at once; otherwise',
    ' * it joins the queue, and the queue is drained after the pass — every state but the last settled',
    ' * immediately so it is observable, the last one animating.',
    ' */',
    'export function scheduleGoToState(m: StatesMachine, state: unknown, invoked: boolean): void {',
    '  const pendingTarget = m.queue.length > 0 ? m.queue[m.queue.length - 1].state : m.state;',
    '  if (state && pendingTarget === state) {',
    '    if (invoked) m.listeners().unchanged?.();',
    '    return;',
    '  }',
    '  m.queue.push({ state, invoked });',
    '  if (m.scheduled) return;',
    '  m.scheduled = true;',
    '  queueMicrotask(() => drainQueue(m));',
    '}',
    '',
    '/** The drain — exported so a test can run the pass by hand at chosen instants. */',
    'export function drainQueue(m: StatesMachine): void {',
    '  m.scheduled = false;',
    '  // Drained before the loop, so a request made *by* one of these signals starts a fresh pass.',
    '  const requested = m.queue.splice(0, m.queue.length);',
    '  for (let i = 0; i < requested.length; i++) {',
    '    goToState(m, requested[i].state, i < requested.length - 1, requested[i].invoked);',
    '  }',
    '}',
    '',
    '/** `Toggle`: the next state in the list, wrapping round after the last. */',
    'export function toggleState(m: StatesMachine): void {',
    '  const states = m.def.states;',
    '  if (!states.length) return;',
    '  const idx = states.indexOf(m.state ?? states[0]);',
    '  const nextIdx = (idx + 1) % states.length;',
    '  scheduleGoToState(m, states[nextIdx], true);',
    '}',
    '',
    'export function snapshotOf<V extends Record<string, ValueDef<unknown>>>(m: StatesMachine): StatesSnapshot<V> {',
    '  return { state: m.state ?? m.def.states[0], values: { ...m.values } as ValuesOf<V>, error: m.error };',
    '}',
    '',
    '// ---- the hook ---------------------------------------------------------------------------------------',
    '',
    'export interface StatesHandle<V extends Record<string, ValueDef<unknown>>> extends StatesSnapshot<V> {',
    '  /** `To <state>` — an action port, so Done/Unchanged/Failure report. */',
    '  goTo(state: string): void;',
    '  /** `Toggle`. */',
    '  toggle(): void;',
    '  /** The `State` input — a setter, which reports nothing but a Failure. */',
    '  follow(state: unknown): void;',
    '}',
    '',
    '/**',
    ' * A `States` node: the state it is in, its values (moving between states), its last Error, and the',
    ' * three ways to ask it to move. `listeners` are the node\'s signal outputs; the latest ones passed are',
    ' * the ones called. The machine lives in a ref and its tween dies with the component.',
    ' */',
    'export function useStates<V extends Record<string, ValueDef<unknown>>>(',
    '  def: StatesDef<V>,',
    '  start?: string,',
    '  listeners?: StatesListeners',
    '): StatesHandle<V> {',
    '  const latest = useRef(listeners);',
    '  latest.current = listeners;',
    '  const machineRef = useRef<StatesMachine | null>(null);',
    '  if (machineRef.current === null) {',
    '    machineRef.current = createStatesMachine(def as StatesDef<Record<string, ValueDef<unknown>>>, start, () => latest.current ?? {});',
    '  }',
    '  const m = machineRef.current;',
    '  const [snapshot, setSnapshot] = useState<StatesSnapshot<V>>(() => snapshotOf<V>(m));',
    '  m.publish = () => setSnapshot(snapshotOf<V>(m));',
    '  useEffect(() => () => stopRun(m.run), [m]);',
    '  const api = useRef({',
    '    goTo: (state: string) => scheduleGoToState(m, state, true),',
    '    toggle: () => toggleState(m),',
    '    follow: (state: unknown) => scheduleGoToState(m, state, false)',
    '  }).current;',
    '  return { ...snapshot, goTo: api.goTo, toggle: api.toggle, follow: api.follow };',
    '}',
    ''
  ].join('\n');
}
